version: "3.9"

networks:
  case01-net:
    driver: overlay

services:
  case01-web:
    image: nginx:alpine
    networks:
      - case01-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.case01-web==true
      restart_policy:
        condition: any

  case01-ping:
    image: alpine:3.19
    command: ["/bin/sh", "-c", "sleep 3600"]
    networks:
      - case01-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.case01-ping==true
      restart_policy:
        condition: any

  vm-runner-linux:
    image: ${VM_RUNNER_LINUX_IMAGE:-poc/vm-runner-linux:latest}
    network_mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.vm-capable==true
      restart_policy:
        condition: any
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/kvm
      - /dev/net/tun
    environment:
      VM_NAME: swarm-lab-linux-usable
      VM_MAC: 52:54:00:ab:cd:41
      VM_DISK: /var/lib/vmrunner/images/linux.qcow2
      VM_SEED: /var/lib/vmrunner/seeds/linux-seed.iso
      VM_NET_MODE: bridge
      VM_BRIDGE: br0
      VM_SSH_USER: ubuntu
    volumes:
      - /dev/kvm:/dev/kvm
      - /var/lib/vmrunner/images:/var/lib/vmrunner/images
      - /var/lib/vmrunner/seeds:/var/lib/vmrunner/seeds
      - ${VM_RUNNER_KEYS_DIR_HOST:-/var/lib/vmrunner/keys}:${VM_RUNNER_KEYS_DIR_CONTAINER:-/var/lib/vmrunner/keys}:ro
