version: "3.9"

networks:
  demo-net:
    driver: overlay

services:
  demo-web:
    image: nginx:alpine
    networks:
      - demo-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.case00-web==true
      restart_policy:
        condition: any

  demo-ping:
    image: alpine:3.19
    command: ["/bin/sh", "-c", "sleep 3600"]
    networks:
      - demo-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.case00-ping==true
      restart_policy:
        condition: any
